name: portfolio_personal
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^10.0.1
  bloc: ^8.1.4
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_font_icons: ^2.2.7
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/
      - assets/pdf/
      - assets/images/
      - assets/images/avatar.png