name: portfolio_personal
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.3.0+1
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_font_icons: ^2.2.7
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  auto_route_generator: ^9.3.1
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
